name: Build Test APK

on:
  workflow_dispatch:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-env

      - name: Test Build
        run: ./gradlew assembleDebug

      - name: Export Artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 2
          name: apk-test
          path: |
            app/build/outputs/apk/debug/app-debug.apk
